import { PrimaryNav, StatesType } from './types';

// Importing Icons
import CameraIcon from '../../public/icons/camera.svg';
import BullhornIcon from '../../public/icons/bullhorn.svg';
import PaletsIcon from '../../public/icons/palets.svg';
import BriefcaseIcon from '../../public/icons/briefcase.svg';
import DollarIcon from '../../public/icons/dollar.svg';
import LeafIcon from '../../public/icons/leaf.svg';
import CodeIcon from '../../public/icons/code.svg';
import BarberIcon from '../../public/icons/barber.svg';
import MusicIcon from '../../public/icons/music.svg';

/* eslint import/prefer-default-export: "off" */
export const categoryMenuItems: PrimaryNav[] = [
  {
    id: 1,
    title: 'Photography',
    icon: CameraIcon,
    active: true,
    submenuItems: [
      {
        id: 1,
        title: 'Photography',
        imgUrl: '/category/photography.jpg',
        totalGraduates: 1234,
      },
      {
        id: 2,
        title: 'iPhone & Android Photography',
        imgUrl: '/category/mobile-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 3,
        title: 'Video Production',
        imgUrl: '/category/video-production.jpg',
        totalGraduates: 34,
      },
      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 5,
        title: 'Adobe Lightroom',
        imgUrl: '/category/adobe-lightroom.jpg',
        totalGraduates: 34,
      },
      {
        id: 6,
        title: 'Online Photoshop',
        imgUrl: '/category/photoshop.jpg',
        totalGraduates: 34,
      },
      {
        id: 7,
        title: 'Video Editing',
        imgUrl: '/category/video-editing.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 2,
    title: 'Marketing',
    icon: BullhornIcon,
    active: false,
    submenuItems: [
      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 5,
        title: 'Adobe Lightroom',
        imgUrl: '/category/adobe-lightroom.jpg',
        totalGraduates: 34,
      },
      {
        id: 6,
        title: 'Online Photoshop',
        imgUrl: '/category/photoshop.jpg',
        totalGraduates: 34,
      },
      {
        id: 7,
        title: 'Video Editing',
        imgUrl: '/category/video-editing.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 3,
    title: 'Design',
    icon: PaletsIcon,
    active: false,
    submenuItems: [
      {
        id: 3,
        title: 'Video Production',
        imgUrl: '/category/video-production.jpg',
        totalGraduates: 34,
      },
      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 5,
        title: 'Adobe Lightroom',
        imgUrl: '/category/adobe-lightroom.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 4,
    title: 'Business & Analytics',
    icon: BriefcaseIcon,
    active: false,
    submenuItems: [
      {
        id: 1,
        title: 'Photography',
        imgUrl: '/category/photography.jpg',
        totalGraduates: 1234,
      },
      {
        id: 2,
        title: 'iPhone & Android Photography',
        imgUrl: '/category/mobile-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 3,
        title: 'Video Production',
        imgUrl: '/category/video-production.jpg',
        totalGraduates: 34,
      },
      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 5,
    title: 'Finance',
    icon: DollarIcon,
    active: false,
    submenuItems: [
      {
        id: 2,
        title: 'iPhone & Android Photography',
        imgUrl: '/category/mobile-photography.jpg',
        totalGraduates: 34,
      },

      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 6,
    title: 'Health Wellness',
    icon: LeafIcon,
    active: false,
    submenuItems: [
      {
        id: 1,
        title: 'Photography',
        imgUrl: '/category/photography.jpg',
        totalGraduates: 1234,
      },
      {
        id: 2,
        title: 'iPhone & Android Photography',
        imgUrl: '/category/mobile-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 3,
        title: 'Video Production',
        imgUrl: '/category/video-production.jpg',
        totalGraduates: 34,
      },
      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 7,
    title: 'Technology',
    icon: CodeIcon,
    active: false,
    submenuItems: [
      {
        id: 1,
        title: 'Photography',
        imgUrl: '/category/photography.jpg',
        totalGraduates: 1234,
      },
      {
        id: 2,
        title: 'iPhone & Android Photography',
        imgUrl: '/category/mobile-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 3,
        title: 'Video Production',
        imgUrl: '/category/video-production.jpg',
        totalGraduates: 34,
      },
      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 5,
        title: 'Adobe Lightroom',
        imgUrl: '/category/adobe-lightroom.jpg',
        totalGraduates: 34,
      },
      {
        id: 6,
        title: 'Online Photoshop',
        imgUrl: '/category/photoshop.jpg',
        totalGraduates: 34,
      },
      {
        id: 7,
        title: 'Video Editing',
        imgUrl: '/category/video-editing.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 8,
    title: 'Arts & Hobbies',
    icon: PaletsIcon,
    active: false,
    submenuItems: [
      {
        id: 1,
        title: 'Photography',
        imgUrl: '/category/photography.jpg',
        totalGraduates: 1234,
      },
      {
        id: 2,
        title: 'iPhone & Android Photography',
        imgUrl: '/category/mobile-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 3,
        title: 'Video Production',
        imgUrl: '/category/video-production.jpg',
        totalGraduates: 34,
      },
      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 5,
        title: 'Adobe Lightroom',
        imgUrl: '/category/adobe-lightroom.jpg',
        totalGraduates: 34,
      },
      {
        id: 6,
        title: 'Online Photoshop',
        imgUrl: '/category/photoshop.jpg',
        totalGraduates: 34,
      },
      {
        id: 7,
        title: 'Video Editing',
        imgUrl: '/category/video-editing.jpg',
        totalGraduates: 34,
      },
      {
        id: 8,
        title: 'Online Photoshop',
        imgUrl: '/category/photoshop.jpg',
        totalGraduates: 34,
      },
      {
        id: 9,
        title: 'Video Editing',
        imgUrl: '/category/video-editing.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 9,
    title: 'Beauty',
    icon: BarberIcon,
    active: false,
    submenuItems: [
      {
        id: 6,
        title: 'Online Photoshop',
        imgUrl: '/category/photoshop.jpg',
        totalGraduates: 34,
      },
      {
        id: 7,
        title: 'Video Editing',
        imgUrl: '/category/video-editing.jpg',
        totalGraduates: 34,
      },
    ],
  },
  {
    id: 10,
    title: 'Music',
    icon: MusicIcon,
    active: false,
    submenuItems: [
      {
        id: 4,
        title: 'Weeding Photography',
        imgUrl: '/category/weeding-photography.jpg',
        totalGraduates: 34,
      },
      {
        id: 5,
        title: 'Adobe Lightroom',
        imgUrl: '/category/adobe-lightroom.jpg',
        totalGraduates: 34,
      },
      {
        id: 6,
        title: 'Online Photoshop',
        imgUrl: '/category/photoshop.jpg',
        totalGraduates: 34,
      },
    ],
  },
];

export const states: StatesType[] = [
  {
    id: 1,
    title: 'Andhra Pradesh',
    active: true,
    cities: [
      'Anantapur',
      'Chittoor',
      'East Godavari',
      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'YSR',
    ],
  },
  {
    id: 2,
    title: 'Amaravati',
    active: false,
    cities: [
      'East Godavari',
      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'YSR',
    ],
  },
  {
    id: 3,
    title: 'Itanagar',
    active: false,
    cities: [
      'Anantapur',
      'Chittoor',
      'East Godavari',

      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'YSR',
    ],
  },
  {
    id: 4,
    title: 'Assam',
    active: false,
    cities: [
      'Anantapur',
      'Chittoor',
      'East Godavari',
      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
    ],
  },
  {
    id: 5,
    title: 'Bihar',
    active: false,
    cities: [
      'East Godavari',
      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'YSR',
    ],
  },
  {
    id: 6,
    title: 'Raipur',
    active: false,
    cities: [
      'Anantapur',
      'Chittoor',
      'East Godavari',
      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'YSR',
    ],
  },
  {
    id: 7,
    title: 'Haryana',
    active: false,
    cities: [
      'Anantapur',
      'Chittoor',
      'East Godavari',
      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
    ],
  },
  {
    id: 8,
    title: 'Andhra Pradesh',
    active: false,
    cities: [
      'Anantapur',

      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'YSR',
    ],
  },
  {
    id: 9,
    title: 'Amaravati',
    active: false,
    cities: [
      'Anantapur',
      'Chittoor',
      'East Godavari',

      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'YSR',
    ],
  },
  {
    id: 10,
    title: 'Itanagar',
    active: false,
    cities: [
      'Guntur',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'YSR',
    ],
  },
];

export const serviceData = [
  {
    id: 1,
    type: 'mentor',
    isAvailable: true,
    isNew: true,
    mentorName: 'Dalvik Loger',
    price: 420,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    authors: 'Nate Taylor, Toby and Smith',
    rating: 4,
    offer: 30,
    imgUrl: '/popular-mentor-1.jpg',
  },
  {
    id: 2,
    type: 'live-class',
    title: 'Photography Masterclass: A Complete Guide to Photography',
    price: 130,
    author: 'Nate Taylor, Toby and Smith',
    new: false,
    star: 4,
    offer: 30,
    imgUrl: 'popular-mentor-2.jpg',
  },
  {
    id: 3,
    type: 'workshop',
    title: 'Photography Masterclass: A Complete Guide to Photography',
    price: 522,
    author: 'Nate Taylor, Toby and Smith',
    new: true,
    star: 4,
    offer: 30,
    imgUrl: 'popular-mentor-1.jpg',
  },
  {
    id: 4,
    type: 'prime-pack',
    title: 'Photography Masterclass: A Complete Guide to Photography',
    price: 156,
    author: 'Nate Taylor, Toby and Smith',
    new: false,
    star: 4,
    offer: 30,
    imgUrl: 'popular-mentor-2.jpg',
  },
  {
    id: 5,
    type: 'mentor',
    isAvailable: true,
    isNew: true,
    mentorName: 'Dalvik Loger',
    price: 420,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    authors: 'Nate Taylor, Toby and Smith',
    rating: 4,
    offer: 30,
    imgUrl: '/popular-mentor-2.jpg',
  },
  {
    id: 6,
    type: 'prime-pack',
    title: 'Photography Masterclass: A Complete Guide to Photography',
    price: 897,
    author: 'Nate Taylor, Toby and Smith',
    new: true,
    star: 4,
    offer: 30,
    imgUrl: 'popular-mentor-2.jpg',
  },
];

export const mentorSliderData = [
  {
    id: 1,
    type: 'mentor',
    isAvailable: true,
    isNew: true,
    mentorName: 'Dalvik Loger',
    price: 420,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    authors: 'Nate Taylor, Toby and Smith',
    rating: 4,
    offer: 30,
    imgUrl: '/popular-mentor-1.jpg',
  },
  {
    id: 2,
    type: 'mentor',
    isAvailable: true,
    isNew: true,
    mentorName: 'Dalvik Loger',
    price: 420,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    authors: 'Nate Taylor, Toby and Smith',
    rating: 4,
    offer: 30,
    imgUrl: '/popular-mentor-2.jpg',
  },
  {
    id: 3,
    type: 'mentor',
    isAvailable: true,
    isNew: true,
    mentorName: 'Dalvik Loger',
    price: 420,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    authors: 'Nate Taylor, Toby and Smith',
    rating: 4,
    offer: 30,
    imgUrl: '/popular-mentor-1.jpg',
  },
  {
    id: 4,
    type: 'mentor',
    isAvailable: true,
    isNew: true,
    mentorName: 'Dalvik Loger',
    price: 420,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    authors: 'Nate Taylor, Toby and Smith',
    rating: 4,
    offer: 30,
    imgUrl: '/popular-mentor-2.jpg',
  },
  {
    id: 5,
    type: 'mentor',
    isAvailable: true,
    isNew: true,
    mentorName: 'Dalvik Loger',
    price: 420,
    title: 'Photography Masterclass: A Complete Guide to Photography',
    authors: 'Nate Taylor, Toby and Smith',
    rating: 4,
    offer: 30,
    imgUrl: '/popular-mentor-1.jpg',
  },
];
